import os

# 创建标准环境
env = Environment(CPPPATH=[
    "../Addons/godot-cpp/include",        # godot-cpp 头文件
    "../Addons/godot-cpp/gen/include",    # 生成的 API 头文件
    "../Addons/godot-cpp/gdextension",
])

# 链接静态库
env.Append(LIBPATH=["../Addons/godot-cpp/bin"])
env.Append(LIBS=["godot-cpp.windows.template_debug.x86_64"])
env.Append(CPPPATH=["../Addons/godot-cpp/gdextension"])

# 编译选项
env.Append(CXXFLAGS=["-std=c++17"])

# 源文件路径
sources = Glob("src/*.cpp")

# 输出目标 DLL
target = "build/simple_input"

env.SharedLibrary(target=target, source=sources)
